parameters:
    extensions_option_importer_connector.job.job_parameters.csv_option_importer_import.class: Extensions\Bundle\OptionImporterConnectorBundle\Job\JobParameters\ProductOptionsCsvImport

services:
    extensions_option_importer_connector.job.job_parameters.csv_option_importer_import:
        class: '%extensions_option_importer_connector.job.job_parameters.csv_option_importer_import.class%'
        arguments:
            - '@pim_connector.job.job_parameters.default_values_provider.product_csv_import'
            - '@pim_connector.job.job_parameters.constraint_collection_provider.product_csv_import'
            - ['%extensions_option_importer_connector.job_name.csv_option_importer_import%']
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }