parameters:
    extensions_option_importer_connector.connector_name.csv: Extensions Option Importer CSV Connector
    extensions_option_importer_connector.job_name.csv_option_importer_import: 'csv_option_importer_import'

services:
    ns.product_options_connector.job.csv_option_importer_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%extensions_option_importer_connector.job_name.csv_option_importer_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@extensions_option_importer_connector.step.options_creator'
        tags:
            - { name: akeneo_batch.job, connector: '%extensions_option_importer_connector.connector_name.csv%', type: '%pim_connector.job.import_type%' }
