parameters:
    extensions_option_importer_connector.reader.file.csv_product.class: Extensions\Bundle\OptionImporterConnectorBundle\Reader\ProductReader

services:
    extensions_option_importer_connector.reader.file.csv_product:
        class: '%extensions_option_importer_connector.reader.file.csv_product.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@extensions_option_importer_connector.array_converter.flat.product'
            - '@pim_connector.reader.file.media_path_transformer'
            - []